version: '3'
services:
  risque:
    image: risque
    ports:
      - "8084:8084"
    networks:
      - my-network
    depends_on:
      - gateway

  gateway:
    image: gateway
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      - front

networks:
  my-network:
    driver: bridge